---
- name: install docker components in version {{ docker_version }}
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
