---
- name: Prepare OS
  block:
    - import_tasks: update_os.yml
    - import_tasks: add_repo.yml

- name: Install docker
  block:
    - import_tasks: docker_users.yml
    - import_tasks: docker_install.yml
