---
- name: remove old docker components
  apt:
    name: "{{ remove_docker_components }}"
    state: absent

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install curl
  apt:
    name: curl

- name: install os dependencies
  apt:
    name: "{{ os_packages }}"
    state: present
